# Async And HTTP

- [For more details click here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing)
- [For more details click here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises)

- What is Async Code ?
- Working with Callbacks
- Promises
- async/await

## What is Async Code ?

- JS is single threaded
- JS can only execute one task at a time.
- Code executes step by step in order.
- IN general Javascript executes the code step by step.
- Lets asume if there is few code like this

```
console.log('Initial Code');
// fetch data from network
// other operation
```

- In the above case if the second step takes time to fetch data from server, then the 3rd operations need to wait.
- For that we have to write in such a way that it will execute the second step and also continue execute the 3rd task

## we can do this using callback

```
const button = document.querySelector('button');
const output = document.querySelector('p');

function trackUserHandler() {
  console.log('Clicked!');
}

button.addEventListener('click', trackUserHandler);
```

<img src="https://github.com/spdobest/JavaScriptUdemy/blob/master/ReadMe/images/callBack.png" />
<table>
<tr>
<td>
  <img src="https://github.com/spdobest/JavaScriptUdemy/blob/master/ReadMe/images/asyncCode.png" width="500" height="300" /> 
 </td>
<td>
<img src="https://github.com/spdobest/JavaScriptUdemy/blob/master/ReadMe/images/asyncCodeExecution.png" width="600" height="300" />
</td>
</tr>
  <tr>
<td>
  <img src="https://github.com/spdobest/JavaScriptUdemy/blob/master/ReadMe/images/howCodeExecute.png" width="500" height="300" /> 
 </td>
<td>
<img src="https://github.com/spdobest/JavaScriptUdemy/blob/master/ReadMe/images/eventLoopQueAsyncCode.png" width="500" height="300" />
</td>
</tr>
</table>

## Promises

- Callback hell

```
getCurrentPosition(() =>{
  setTimeOut(() =>{
      console.log('Executing');
  },2000);
})

```

- To overcome the complexity and lenghy of call back, promise can be used.
- How to declare a promise

```
const promise = new Promise((resolve, reject) =>{

});
```

- Promise takes 2 parameters resolve and reject
- For Example

```
const setTimer = (duration) => {
  const promise = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("Done!");
    }, duration);
  });
  return promise;
};

function trackUserHandler() {
  navigator.geolocation.getCurrentPosition(
    (posData) => {
      setTimer(2000).then((data) => {
        console.log(data, posData);
      });
    },
    (error) => {
      console.log(error);
    }
  );
  setTimer(1000).then(() => {
    console.log("Timer done!");
  });
  console.log("Getting position...");
}

button.addEventListener("click", trackUserHandler);

```

- **then** is used to get the values returned from promise

## Promise chain

- By chaining the promises we can perform one promise after another

```
const getPosition = opts => {
  const promise = new Promise((resolve, reject) => {
    navigator.geolocation.getCurrentPosition(
      success => {
        resolve(success);
      },
      error => {},
      opts
    );
  });
  return promise;
};

const setTimer = duration => {
  const promise = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('Done!');
    }, duration);
  });
  return promise;
};

function trackUserHandler() {
  let positionData;
  getPosition()
    .then(posData => {
      positionData = posData;
      return setTimer(2000);
    })
    .then(data => {
      console.log(data, positionData);
    });
  setTimer(1000).then(() => {
    console.log('Timer done!');
  });
  console.log('Getting position...');
}

button.addEventListener('click', trackUserHandler);
```

## Promise Error Handling

- If a promise returns failure or exception occurs
- the reject parameter returns the exception, we can handle that using another block after then like this
- Look at the below code

```
const getPosition = opts => {
  const promise = new Promise((resolve, reject) => {
    navigator.geolocation.getCurrentPosition(
      success => {
        resolve(success);
      },
      error => {
        reject(error);
      },
      opts
    );
  });
  return promise;
};

const setTimer = duration => {
  const promise = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('Done!');
    }, duration);
  });
  return promise;
};

async function trackUserHandler() {
  // let positionData;
  let posData;
  let timerData;
  try {
    posData = await getPosition();
    timerData = await setTimer(2000);
  } catch (error) {
    console.log(error);
  }
  console.log(timerData, posData);
}

button.addEventListener('click', trackUserHandler);
```

```
navigator.geolocation.getCurrentPosition(
      success => {
        resolve(success);
      },
      error => {
        reject(error);
      },
      opts
    );
```

- THis like of code show the error handling
- THis err block is more complex by writting nested blocks
- We can avoid this using catch block

```
getPosition()
.then( (res ) =>{
 console.log('Result');
})
.catch((err) =>{
  console.log('Error');
})
```

- the catch block position matters code execution
- If you put catch block after multiple then block, that means at the end of the last then
- Then if the initial promise return any exception, then it will skip the rest nested then block and it will execute the catch block
- If you want to execute the 2nd promise if the first promise return any error, then put catch block after the first then block.
- So that it will catch and print the error and then it will execute the 2nd promise

## Promise State and finally

- You learned about the different promise states:
- **PENDING** => Promise is doing work, neither then() nor catch() executes at this moment
- **RESOLVED** => Promise is resolved => then() executes
- **REJECTED** => Promise was rejected => catch() executes
- When you have another then() block after a catch() or then() block, the promise re-enters PENDING mode (keep in mind: then() and catch() always return a new promise - either not resolving to anything or resolving to what you return inside of then()). Only if there are no more then() blocks left, it enters a new, final mode: SETTLED.
- Once SETTLED, you can use a special block - finally() - to do final cleanup work. finally() is reached no matter if you resolved or rejected before.
- Here's an example:
- FInally block is same as finally in java
- Wether exception occurs or not, finally block will be execute

```
    somePromiseCreatingCode()
        .then(firstResult => {
            return 'done with first promise';
        })
        .catch(err => {
            // would handle any errors thrown before
            // implicitly returns a new promise - just like then()
        })
        .finally(() => {
            // the promise is settled now - finally() will NOT return a new promise!
            // you can do final cleanup work here
        });
```

## async and await

```
async function trackUserHandler() {
  let positionData;
  let posData;
  let timerData;
  try {
    posData = await getPosition();
    timerData = await setTimer(2000);
  } catch (error) {
    console.log(error);
  }
  console.log(timerData, posData);
  setTimer(1000).then(() => {
    console.log('Timer done!');
  });
  console.log('Getting position...');
  }
```

- if we add await before a function, that means it will wait for the call to get result or fail
- posData = await getPosition();, this line of code execute and get the result.
- After that only `timerData = await setTimer(2000);` code will execute

## async await error handling

- We can handle error using try catch block.
- Here is the example

```
try {
    posData = await getPosition();
    timerData = await setTimer(2000);
  } catch (error) {
    console.log(error);
  }
```

## async/await vs raw Promise

- async and await is better in terms oc clean code
- Better performance
-

## promise.all() promise.race()

- Promise.race() will execute the fastest promise, it will print the result of the fastest promise result

```
Promise.race([getPosition(), setTimer(1000)]).then(data => {
   console.log(data);
 });
```

- Promise.all() will execute alll the promises and it will return the combination of the result

```
Promise.all([getPosition(), setTimer(1000)]).then(promiseData => {
  console.log(promiseData);
   });
```

- Promise.allSettled() will execute both the promises and returns the value
- It does not cancel or stop the execution if one promise is failing.

```
Promise.allSettled([getPosition(), setTimer(1000)]).then(promiseData => {
  console.log(promiseData);
});
```
